services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskiqasyncpg

    volumes:
      - .:/postgres_data:/var/lib/postgresql/data/

    ports:
      - 5432:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "taskiqasyncpg"]
      interval: 3s
      timeout: 1s
      retries: 5

    networks:
      - default

volumes:
  postgres_data:
networks:
  default:
    driver: bridge
